name: Go CI

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/**'
      - 'Dockerfile'
      - 'main.go'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'internal/**'
      - 'Dockerfile'
      - 'main.go'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
        cache: false

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: 520291287938.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        password: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}

    - name: Build and push Docker image
      run: |
        IMAGE_URI=520291287938.dkr.ecr.us-east-1.amazonaws.com/devops-profile
        IMAGE_TAG=${GITHUB_SHA::8} 
        docker build -t tokenapp .
        docker tag tokenapp $IMAGE_URI:$IMAGE_TAG
        docker push $IMAGE_URI:$IMAGE_TAG
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        