name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod   # This is the default location for Go modules cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: 520291287938.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        password: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t tokenapp .
        docker tag tokenapp 520291287938.dkr.ecr.us-east-1.amazonaws.com/devops-profile:1.0.3
        docker push 520291287938.dkr.ecr.us-east-1.amazonaws.com/devops-profile:1.0.3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        